@extends('adminlte::page')

@section('title', 'Vouchers')

@section('content_header')
    <div class="d-flex justify-content-between">
        <h1>Vouchers</h1>
        <div>
            <a href="{{ route('vouchers.create') }}" class="btn btn-primary">
                <i class="fas fa-plus"></i> Generate Vouchers
            </a>
            <a href="{{ route('vouchers.print') }}" target="_blank" class="btn btn-success">
                <i class="fas fa-print"></i> Print Vouchers
            </a>
        </div>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-tools">
                        <form action="{{ route('vouchers.index') }}" method="GET" class="form-inline">
                            <select name="router" class="form-control form-control-sm mr-2">
                                <option value="">All Routers</option>
                                @foreach($routers as $router)
                                    <option value="{{ $router }}" {{ request('router') == $router ? 'selected' : '' }}>
                                        {{ $router }}
                                    </option>
                                @endforeach
                            </select>
                            <select name="plan" class="form-control form-control-sm mr-2">
                                <option value="">All Plans</option>
                                @foreach($plans as $plan)
                                    <option value="{{ $plan->id }}" {{ request('plan') == $plan->id ? 'selected' : '' }}>
                                        {{ $plan->name }}
                                    </option>
                                @endforeach
                            </select>
                            <select name="status" class="form-control form-control-sm mr-2">
                                <option value="">All Status</option>
                                <option value="1" {{ request('status') == '1' ? 'selected' : '' }}>Used</option>
                                <option value="0" {{ request('status') === '0' ? 'selected' : '' }}>Unused</option>
                            </select>
                            <input type="text" name="search" class="form-control form-control-sm mr-2" 
                                   placeholder="Search Voucher Code" 
                                   value="{{ request('search') }}">
                            <button type="submit" class="btn btn-sm btn-default">
                                <i class="fas fa-filter"></i> Filter
                            </button>
                        </form>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Voucher Code</th>
                                    <th>Type</th>
                                    <th>Router</th>
                                    <th>Plan</th>
                                    <th>Status</th>
                                    <th>Generated By</th>
                                    <th>Created</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($vouchers as $voucher)
                                    <tr>
                                        <td>
                                            <div class="voucher-code-container">
                                                <code class="voucher-code hidden-code">
                                                    <span class="dots">••••••</span>
                                                    <span class="actual-code">{{ $voucher->code }}</span>
                                                </code>
                                                @if(!$voucher->is_used)
                                                    <button class="btn btn-xs btn-link copy-btn" 
                                                            data-code="{{ $voucher->code }}"
                                                            title="Copy Voucher Code">
                                                        <i class="fas fa-copy"></i>
                                                    </button>
                                                @endif
                                            </div>
                                        </td>
                                        <td>{{ $voucher->type }}</td>
                                        <td>{{ $voucher->routers }}</td>
                                        <td>{{ $voucher->plan->name }}</td>
                                        <td>
                                            @if($voucher->is_used)
                                                <span class="badge badge-success">Used</span>
                                            @else
                                                <span class="badge badge-warning">Unused</span>
                                            @endif
                                        </td>
                                        <td>
                                            @if($voucher->generated_by)
                                                {{ $voucher->generatedBy->name ?? 'Unknown' }}
                                            @else
                                                -
                                            @endif
                                        </td>
                                        <td>{{ $voucher->created_at->format('Y-m-d H:i') }}</td>
                                        <td>
                                            <div class="btn-group">
                                                <a href="{{ route('vouchers.show', $voucher) }}" 
                                                   class="btn btn-sm btn-info"
                                                   title="View Details">
                                                    <i class="fas fa-eye"></i>
                                                </a>
                                                @if(!$voucher->is_used)
                                                    <form action="{{ route('vouchers.destroy', $voucher) }}" 
                                                          method="POST" 
                                                          onsubmit="return confirm('Are you sure you want to delete this voucher?');">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" 
                                                                class="btn btn-sm btn-danger" 
                                                                title="Delete">
                                                            <i class="fas fa-trash"></i>
                                                        </button>
                                                    </form>
                                                @endif
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <form action="{{ url('vouchers/delete-old') }}" method="POST" class="d-inline">
                        @csrf
                        @method('DELETE')
                        <button type="submit" 
                                class="btn btn-warning btn-sm" 
                                onclick="return confirm('Are you sure you want to delete all unused vouchers older than 3 months? This action cannot be undone.')">
                            <i class="fas fa-trash"></i> Delete Old Vouchers
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
<style>
    .voucher-code-container {
        display: flex;
        align-items: center;
        gap: 5px;
    }

    .voucher-code {
        position: relative;
        cursor: pointer;
        padding: 2px 6px;
        background: #f8f9fa;
        border-radius: 3px;
    }

    .voucher-code .dots {
        display: inline;
    }

    .voucher-code .actual-code {
        display: none;
        user-select: all;
    }

    .voucher-code:hover .dots {
        display: none;
    }

    .voucher-code:hover .actual-code {
        display: inline;
    }

    .voucher-code .dots,
    .voucher-code .actual-code {
        transition: all 0.2s ease;
    }

    .voucher-code:hover {
        background: #e9ecef;
    }
</style>
@stop

@section('js')
<script>
    $(document).ready(function() {
        $('.copy-btn').click(function(e) {
            e.preventDefault();
            e.stopPropagation();
            
            const code = $(this).data('code');
            navigator.clipboard.writeText(code).then(function() {
                toastr.success('Voucher code copied to clipboard');
            }, function(err) {
                toastr.error('Could not copy text');
            });
        });
    });
</script>
@stop
