@extends('adminlte::page')

@section('title', 'Voucher Details')

@section('content_header')
    <div class="d-flex justify-content-between align-items-center">
        <h1>Voucher Details</h1>
        <div>
            @if(!$voucher->is_used)
                <form action="{{ route('vouchers.destroy', $voucher) }}" 
                      method="POST" 
                      class="d-inline" 
                      onsubmit="return confirm('Are you sure you want to delete this voucher?');">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm">
                        <i class="fas fa-trash"></i> Delete Voucher
                    </button>
                </form>
            @endif
            <a href="{{ route('vouchers.index') }}" class="btn btn-secondary btn-sm ml-2">
                <i class="fas fa-arrow-left"></i> Back to Vouchers
            </a>
        </div>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Voucher Information</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <strong>Voucher Code:</strong>
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" value="{{ $voucher->code }}" readonly>
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="button" 
                                            onclick="copyToClipboard('{{ $voucher->code }}')">
                                        <i class="fas fa-copy"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <strong>Status:</strong>
                            @if($voucher->is_used)
                                <span class="badge badge-success">Used</span>
                            @else
                                <span class="badge badge-warning">Unused</span>
                            @endif
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-md-6">
                            <strong>Type:</strong>
                            <p>{{ $voucher->type }}</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Router:</strong>
                            <p>{{ $voucher->routers }}</p>
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-md-6">
                            <strong>Internet Plan:</strong>
                            <p>{{ $voucher->plan->name }}</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Generated By:</strong>
                            <p>{{ $voucher->generatedBy->name ?? 'Unknown' }}</p>
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-md-6">
                            <strong>Created At:</strong>
                            <p>{{ $voucher->created_at->format('Y-m-d H:i:s') }}</p>
                        </div>
                        @if($voucher->is_used)
                            <div class="col-md-6">
                                <strong>Used By:</strong>
                                @if($voucher->customer)
                                    <p>
                                        <a href="{{ route('customers.show', $voucher->customer) }}">
                                            {{ $voucher->customer->name }} ({{ $voucher->customer->username }})
                                        </a>
                                    </p>
                                @else
                                    <p>-</p>
                                @endif
                            </div>
                        @endif
                    </div>

                    @if($voucher->is_used)
                        <div class="row mt-3">
                            <div class="col-md-6">
                                <strong>Used At:</strong>
                                <p>{{ $voucher->used_at->format('Y-m-d H:i:s') }}</p>
                            </div>
                        </div>
                    @endif

                    <hr>

                    <div class="row mt-4">
                        <div class="col-12 text-center">
                            <strong>QR Code</strong><br>
                            <div class="mt-2">
                                {!! DNS2D::getBarcodeHTML($voucher->code, 'QRCODE', 5, 5) !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    @if(!$voucher->is_used)
                        <button class="btn btn-primary" onclick="printVoucher()">
                            <i class="fas fa-print"></i> Print Voucher
                        </button>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Print Voucher Modal -->
    <div class="modal fade" id="print-voucher-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Print Voucher</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    <div id="voucher-print-content">
                        <h2>{{ config('app.name') }} Voucher</h2>
                        <div class="voucher-details">
                            <p><strong>Code:</strong> {{ $voucher->code }}</p>
                            <p><strong>Plan:</strong> {{ $voucher->plan->name }}</p>
                            <p><strong>Type:</strong> {{ $voucher->type }}</p>
                            <p><strong>Router:</strong> {{ $voucher->routers }}</p>
                        </div>
                        <div class="mt-4">
                            <div class="qrcode">
                                {!! DNS2D::getBarcodeHTML($voucher->code, 'QRCODE', 5, 5) !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="actualPrint()">
                        <i class="fas fa-print"></i> Print
                    </button>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    <style>
        .qrcode {
            display: inline-block;
            padding: 10px;
        }
        @media print {
            body * {
                visibility: hidden;
            }
            #voucher-print-content, 
            #voucher-print-content * {
                visibility: visible;
            }
            #voucher-print-content {
                position: absolute;
                left: 50%;
                top: 50%;
                transform: translate(-50%, -50%);
                text-align: center;
            }
        }
    </style>
@stop

@section('js')
    <script>
        function copyToClipboard(text) {
            navigator.clipboard.writeText(text).then(function() {
                toastr.success('Voucher code copied to clipboard');
            }, function(err) {
                toastr.error('Could not copy text');
            });
        }

        function printVoucher() {
            $('#print-voucher-modal').modal('show');
        }

        function actualPrint() {
            var printContent = document.getElementById('voucher-print-content');
            var originalContents = document.body.innerHTML;
            
            document.body.innerHTML = printContent.innerHTML;
            window.print();
            
            document.body.innerHTML = originalContents;
            location.reload();
        }
    </script>
@stop
